In [50]:
import pandas as pd
import numpy as np

In [2]:
student_df = pd.DataFrame([['Vaibhav',1,'BE-IT'],['Tejaa',2,'CS-IT'],['Dheeraj',3,'ME']], columns = ['Name','Enroll. No.','Qualification'])
student_df

Name  Enroll. No. Qualification
0  Vaibhav            1         BE-IT
1    Tejaa            2         CS-IT
2  Dheeraj            3            ME

# iloc[]
- iloc stands for “integer location” and is a function in the Pandas library.
- It is used to select rows and columns from a Pandas DataFrame or a Series using integer-based indexing.
- Example - my_df = student_df.iloc[[0,2]]


In [3]:
my_df = student_df.iloc[[0,2]]
my_df

Name  Enroll. No. Qualification
0  Vaibhav            1         BE-IT
2  Dheeraj            3            ME

In [7]:
my_df.iloc[[1]]

Name  Enroll. No. Qualification
2  Dheeraj            3            ME

In [11]:
import os

In [8]:
df = pd.read_excel('ERPData.xlsx')
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

# df.head()

- This command will return first five objects from the dataframe.

In [10]:
df.shape

(50, 3)

# df.shape

- This command will return number of rows and columns available in your dataframe / table.

df['Quantity'] or df.Quantity

In [12]:
x = list(df['Quantity'])

In [13]:
x[:5]

[34, 67, 27, 65, 36]

In [14]:
len(x)

50

In [16]:
import numpy as np

In [36]:
x = np.array(df['Quantity'])
x

array([ 34,  67,  27,  65,  36,  78,  31,  29,  10, 120,  34,  58,  76,
        32,  65,  87,  12, 102,  34,  52,  39,  75,  48,  71, 152, 109,
        57,  83,  34,  57,  27,  65,  43, 112,  26,  31,  28,  65,  70,
       145,  34,  57,  31,  38,  42,  69,  85,  29,  75,  39], dtype=int64)

In [37]:
ind = np.where(x>=75)

In [38]:
len(ind)

1

In [39]:
(df.Quantity>=75).sum()
# This command wil return the count of result

13

In [40]:
np.where(df.Location == 'MWH-3')

(array([14, 43, 44, 47], dtype=int64),)

In [41]:
(df.Location == 'MWH-3').sum()

4

In [42]:
ind

(array([ 5,  9, 12, 15, 17, 21, 24, 25, 27, 33, 39, 46, 48], dtype=int64),)

In [43]:
# This command will be used to create a new separate array to store result.
mydf = df.iloc[ind]
mydf

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [44]:
mydf.iloc[[0,1,2]]

# This command will print first 3 records from the selected dataframe.

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76

In [46]:
np.where(df.Location =='MWH-5')

(array([ 3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38], dtype=int64),)

In [48]:
(df.Location =='MWH-5').sum()

11

In [49]:
np.where(df.Quantity >= 100)

(array([ 9, 17, 24, 25, 33, 39], dtype=int64),)

In [50]:
(df.Quantity >= 100).sum()

6

In [52]:
(df.Location =='MWH-5').sum() & (df.Quantity >= 100).sum()

2

In [53]:
(df.Location =='MWH-5').sum() and (df.Quantity >= 100).sum()

6

In [54]:
ind = np.where((df['Quantity'] >= 100) & (df['Location'] == 'MWH-5'))
ind

(array([17, 33], dtype=int64),)

In [55]:
mydf = df.iloc[ind]

In [56]:
mydf

MaterialID Location  Quantity
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

In [59]:
ind = np.where((df['MaterialID']=='TMI-43T') | (df['Quantity'] >= 100))
ind

(array([ 0,  5,  6,  7,  9, 12, 13, 14, 17, 18, 19, 20, 21, 24, 25, 31, 32,
        33, 39], dtype=int64),)

In [60]:
mydf = df.iloc[ind]
mydf

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

In [61]:
((df['MaterialID']=='TMI-43T') | (df['Quantity'] >= 100)).sum()

19

In [62]:
len(ind[0])

19

In [63]:
ind = np.where(df.Quantity <= 25)

In [64]:
ind

(array([ 8, 16], dtype=int64),)

In [65]:
len(ind[0])

2

In [66]:
my_df = df.drop(ind[0])
# This command will drop the selected records

In [67]:
my_df.shape

(48, 3)

In [68]:
list1 = []

In [69]:
x = list(df.Quantity)
y =[]

In [70]:
for ctr in x:
    if ctr >= 50:
        y.append('Scrap')
    else:
        y.append('Useful')

In [71]:
x[:5]

[34, 67, 27, 65, 36]

In [72]:
y[:5]

['Useful', 'Scrap', 'Useful', 'Scrap', 'Useful']

In [73]:
df['Status'] = y

In [74]:
y

['Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Scrap',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Useful',
 'Scrap',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Useful',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful']

In [75]:
df

MaterialID Location  Quantity  Status
0     TMI-43T    MWH-4        34  Useful
1     AXCP-78    MWH-1        67   Scrap
2     LXCV-21    MWH-2        27  Useful
3     AXCP-78    MWH-5        65   Scrap
4     AXCP-78    MWH-4        36  Useful
5     TMI-43T    MWH-4        78   Scrap
6     TMI-43T    MWH-4        31  Useful
7     TMI-43T    MWH-2        29  Useful
8     GCVB-79    MWH-2        10  Useful
9     TMI-43T    MWH-1       120   Scrap
10    SDRT-67    MWH-1        34  Useful
11    SDRT-67    MWH-4        58   Scrap
12    TMI-43T    MWH-4        76   Scrap
13    TMI-43T    MWH-4        32  Useful
14    TMI-43T    MWH-3        65   Scrap
15    GCVB-79    MWH-2        87   Scrap
16    SDRT-67    MWH-5        12  Useful
17    SDRT-67    MWH-5       102   Scrap
18    TMI-43T    MWH-4        34  Useful
19    TMI-43T    MWH-4        52   Scrap
20    TMI-43T    MWH-4        39  Useful
21    TMI-43T    MWH-4        75   Scrap
22    DDBN-89    MWH-4        48  Useful
23    DDBN-89    MWH-5        71   Scrap
24    AXCP-78    MWH-1       152   Scrap
25    AXCP-78    MWH-1       109   Scrap
26    DDBN-89    MWH-1        57   Scrap
27    LXCV-21    MWH-5        83   Scrap
28    LXCV-21    MWH-5        34  Useful
29    LXCV-21    MWH-5        57   Scrap
30    DDBN-89    MWH-4        27  Useful
31    TMI-43T    MWH-4        65   Scrap
32    TMI-43T    MWH-4        43  Useful
33    TMI-43T    MWH-5       112   Scrap
34    GCVB-79    MWH-5        26  Useful
35    GCVB-79    MWH-2        31  Useful
36    GCVB-79    MWH-2        28  Useful
37    AXCP-78    MWH-5        65   Scrap
38    AXCP-78    MWH-5        70   Scrap
39    AXCP-78    MWH-1       145   Scrap
40    DDBN-89    MWH-1        34  Useful
41    SDRT-67    MWH-1        57   Scrap
42    SDRT-67    MWH-2        31  Useful
43    DDBN-89    MWH-3        38  Useful
44    LXCV-21    MWH-3        42  Useful
45    DDBN-89    MWH-2        69   Scrap
46    AXCP-78    MWH-2        85   Scrap
47    AXCP-78    MWH-3        29  Useful
48    AXCP-78    MWH-1        75   Scrap
49    DDBN-89    MWH-1        39  Useful

In [76]:
df.head()

MaterialID Location  Quantity  Status
0    TMI-43T    MWH-4        34  Useful
1    AXCP-78    MWH-1        67   Scrap
2    LXCV-21    MWH-2        27  Useful
3    AXCP-78    MWH-5        65   Scrap
4    AXCP-78    MWH-4        36  Useful

In [77]:
df.columns

Index(['MaterialID', 'Location', 'Quantity', 'Status'], dtype='object')

In [78]:
x = list(df.columns)

In [79]:
x

['MaterialID', 'Location', 'Quantity', 'Status']

In [80]:
x[0] = 'Name'

In [81]:
df.columns = x

In [83]:
df.head()

Name Location  Quantity  Status
0  TMI-43T    MWH-4        34  Useful
1  AXCP-78    MWH-1        67   Scrap
2  LXCV-21    MWH-2        27  Useful
3  AXCP-78    MWH-5        65   Scrap
4  AXCP-78    MWH-4        36  Useful

In [4]:
df = pd.read_excel('emp_info.xlsx')

In [5]:
df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A746      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [8]:
ind1 = np.where(df['Deptt'].isnull())
ind1

(array([3, 5], dtype=int64),)

In [12]:
ind2 = df.drop(ind1[0], axis = 0)
ind2

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

In [19]:
df1 = df.iloc[ind1]
df1

Name EmpID Deptt  Passport
3   Arjun  A746   NaN  RF453432
5  Chetan   NaN   NaN  ER534867

In [22]:
ind = np.where((df['Deptt'].isnull()) | ((df['EmpID'].isnull())))
ind

(array([3, 5, 6], dtype=int64),)

In [23]:
ind = np.where(df['Passport'].duplicated(keep=False))
ind

(array([0, 2, 3, 4, 6], dtype=int64),)

In [24]:
df.dropna()

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

In [26]:
ind = np.where(df['Passport'].duplicated(keep='last'))
ind

(array([0, 2, 3], dtype=int64),)

In [27]:
ind = np.where(df['Passport'].duplicated(keep='first'))
ind

(array([2, 4, 6], dtype=int64),)

In [28]:
df = pd.read_excel('ERPData.xlsx')

In [29]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [30]:
grp1 = df.groupby('Location')
grp1

In [31]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [32]:
len(grp1.groups)

5

In [33]:
grp1.get_group('MWH-2')

# This command will return specific group

MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [34]:
grp1.agg(np.mean)

# This command will return average/mean of all the values

C:\Users\vaibh\AppData\Local\Temp\ipykernel_3064\4186384218.py:1: FutureWarning: The operation <function mean at 0x000002617E1BF420> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  grp1.agg(np.mean)


Quantity
Location           
MWH-1     80.818182
MWH-2     44.111111
MWH-3     43.500000
MWH-4     48.533333
MWH-5     63.363636

In [35]:
grp1.agg(np.size)

MaterialID  Quantity
Location                      
MWH-1             11        11
MWH-2              9         9
MWH-3              4         4
MWH-4             15        15
MWH-5             11        11

In [37]:
grp1.agg(np.sum)

C:\Users\vaibh\AppData\Local\Temp\ipykernel_3064\2546950891.py:1: FutureWarning: The operation <function sum at 0x000002617E1BDDA0> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  grp1.agg(np.sum)


Quantity
Location          
MWH-1          889
MWH-2          397
MWH-3          174
MWH-4          728
MWH-5          697

In [38]:
r = grp1.agg([np.sum,np.mean])
r

C:\Users\vaibh\AppData\Local\Temp\ipykernel_3064\2418498943.py:1: FutureWarning: ['MaterialID'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  r = grp1.agg([np.sum,np.mean])


Quantity           
              sum       mean
Location                    
MWH-1         889  80.818182
MWH-2         397  44.111111
MWH-3         174  43.500000
MWH-4         728  48.533333
MWH-5         697  63.363636

In [39]:
ind = np.where(r.index == 'MWH-3')

In [40]:
r.iloc[ind]

Quantity      
              sum  mean
Location               
MWH-3         174  43.5

In [41]:
grp2 = df.groupby(['MaterialID','Location'])
grp2.groups

#primary grouping is done on MaterialID
#secondary grouping is done a=on Location

{('AXCP-78', 'MWH-1'): [1, 24, 25, 39, 48], ('AXCP-78', 'MWH-2'): [46], ('AXCP-78', 'MWH-3'): [47], ('AXCP-78', 'MWH-4'): [4], ('AXCP-78', 'MWH-5'): [3, 37, 38], ('DDBN-89', 'MWH-1'): [26, 40, 49], ('DDBN-89', 'MWH-2'): [45], ('DDBN-89', 'MWH-3'): [43], ('DDBN-89', 'MWH-4'): [22, 30], ('DDBN-89', 'MWH-5'): [23], ('GCVB-79', 'MWH-2'): [8, 15, 35, 36], ('GCVB-79', 'MWH-5'): [34], ('LXCV-21', 'MWH-2'): [2], ('LXCV-21', 'MWH-3'): [44], ('LXCV-21', 'MWH-5'): [27, 28, 29], ('SDRT-67', 'MWH-1'): [10, 41], ('SDRT-67', 'MWH-2'): [42], ('SDRT-67', 'MWH-4'): [11], ('SDRT-67', 'MWH-5'): [16, 17], ('TMI-43T', 'MWH-1'): [9], ('TMI-43T', 'MWH-2'): [7], ('TMI-43T', 'MWH-3'): [14], ('TMI-43T', 'MWH-4'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('TMI-43T', 'MWH-5'): [33]}

In [42]:
grp3 = df.groupby(['Location','MaterialID'])
grp3.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [43]:
grp2.agg([np.sum,np.size])

Quantity     
                         sum size
MaterialID Location              
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
DDBN-89    MWH-1         130    3
           MWH-2          69    1
           MWH-3          38    1
           MWH-4          75    2
           MWH-5          71    1
GCVB-79    MWH-2         156    4
           MWH-5          26    1
LXCV-21    MWH-2          27    1
           MWH-3          42    1
           MWH-5         174    3
SDRT-67    MWH-1          91    2
           MWH-2          31    1
           MWH-4          58    1
           MWH-5         114    2
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [44]:
grp3.agg([np.sum,np.size])

Quantity     
                         sum size
Location MaterialID              
MWH-1    AXCP-78         548    5
         DDBN-89         130    3
         SDRT-67          91    2
         TMI-43T         120    1
MWH-2    AXCP-78          85    1
         DDBN-89          69    1
         GCVB-79         156    4
         LXCV-21          27    1
         SDRT-67          31    1
         TMI-43T          29    1
MWH-3    AXCP-78          29    1
         DDBN-89          38    1
         LXCV-21          42    1
         TMI-43T          65    1
MWH-4    AXCP-78          36    1
         DDBN-89          75    2
         SDRT-67          58    1
         TMI-43T         559   11
MWH-5    AXCP-78         200    3
         DDBN-89          71    1
         GCVB-79          26    1
         LXCV-21         174    3
         SDRT-67         114    2
         TMI-43T         112    1

In [45]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [46]:
mydf = df.sort_values('Quantity')
mydf.head()

MaterialID Location  Quantity
8     GCVB-79    MWH-2        10
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27

In [47]:
mydf.tail()

MaterialID Location  Quantity
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
9     TMI-43T    MWH-1       120
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152

In [49]:
mydf = df.sort_values(['Location','MaterialID','Quantity'])
mydf

#In this command sorting preference from left to right

MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
9     TMI-43T    MWH-1       120
46    AXCP-78    MWH-2        85
45    DDBN-89    MWH-2        69
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
2     LXCV-21    MWH-2        27
42    SDRT-67    MWH-2        31
7     TMI-43T    MWH-2        29
47    AXCP-78    MWH-3        29
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
14    TMI-43T    MWH-3        65
4     AXCP-78    MWH-4        36
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
11    SDRT-67    MWH-4        58
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
23    DDBN-89    MWH-5        71
34    GCVB-79    MWH-5        26
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

In [51]:
df1 = pd.read_excel('locations.xlsx', sheet_name = 'Pune')
df2 = pd.read_excel('locations.xlsx', sheet_name = 'Mumbai')

In [52]:
df1

Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [53]:
df2

Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [54]:
pd.merge(df1,df2, on='Subject', how='inner')
#inner means Intersection

Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A

In [55]:
pd.merge(df1,df2, on='Subject', how='outer')
#outer means Union

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5      NaN    Six Sigma     NaN   Vaibhav       A

In [56]:
pd.merge(df1,df2, on='Subject', how='left')

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [57]:
pd.merge(df1,df2, on='Subject', how='right')

Name_x     Subject Grade_x    Name_y Grade_y
0      NaN   Six Sigma     NaN   Vaibhav       A
1  Vaibhav  Statistics       B   Deepika       B
2   Hitesh  CommSkills       A     Arjun       A
3   Rakesh      Python       A    Chetan       A
4    Manoj    MLPython       C  Abhishek       B