# Naive Bayes Algorithm

- probability will be used.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

## Assigning features and label variables

In [ ]:
# First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

## Import Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

### Creating labels

In [ ]:
la = LabelEncoder()

In [ ]:
w_encode = la.fit_transform(weather)
w_encode

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
t_encode = la.fit_transform(temp)
t_encode

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
p_encode = la.fit_transform(play)
p_encode

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

### Combining columns

In [ ]:
features = list(zip(w_encode,t_encode))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

## Modeling

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(features,p_encode)

GaussianNB()

## Prediction

In [ ]:
predict = model.predict([[0,2]])
predict

array([1])

## Evaluation

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

### Confusion Matrix

In [ ]:
confusion_matrix()

### Classification Report

In [ ]:
print(classification_report())

### Accuracy Score

In [ ]:
print(accuracy_score())