In [2]:
import numpy as np
m=np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [3]:
print(m)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [4]:
m.shape

(2, 5)

In [6]:
m.ndim

2

In [7]:
m.size

10

In [8]:
m[0][2]

3

In [9]:
for i in m:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
0


In [10]:
for i in np.nditer(m[::]):
    print(i)

1
2
3
4
5
6
7
8
9
0


In [12]:
n=np.arange(0,101,5)
print(n)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [18]:
n.reshape(3,7)

array([[  0,   5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90,  95, 100]])

In [19]:
from numpy import random

In [21]:
print(random.randint(100))

69


In [22]:
print(random.randint(100,size=(6,6)))

[[43 24 32 16  2  6]
 [36 39 99 69 48 48]
 [ 9  7  8 17 13 14]
 [94 66  9 79 44 97]
 [96 36 92 82 10 24]
 [56  4 57  2 45 11]]


In [24]:
print(random.choice(['a','b','c','d']))

c
