In [6]:
import numpy as np

In [7]:
import pandas as pd

In [10]:
x = np.arange(7)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
x = np.arange(3,7)

In [14]:
x

array([3, 4, 5, 6])

In [15]:
x = np.arange(3,17,4)

In [16]:
x

array([ 3,  7, 11, 15])

In [17]:
x = np.arange(40,6,-2)

In [18]:
x

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8])

In [19]:
type(x)

numpy.ndarray

In [20]:
x+3

array([43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11])

In [21]:
y = [2,8,7,6]

In [22]:
y = np.array(y)

In [23]:
y

array([2, 8, 7, 6])

In [25]:
y = y + 3

In [26]:
y

array([ 5, 11, 10,  9])

In [24]:
type(y)

numpy.ndarray

In [27]:
y = list(y)

In [28]:
y

[5, 11, 10, 9]

In [29]:
type (y)

list

In [30]:
arr = np.array([3,7,5,8])

It is a one dimensional array.

In [32]:
arr2 = np.array([[3,7,5,8],[1,4,3,6]])

It is a two dimensional array.

In [33]:
arr2

array([[3, 7, 5, 8],
       [1, 4, 3, 6]])

In [35]:
arr3 = np.array([[3,7,5,8],[1,4,3,6],[1,9,7,4]])

It is a multi dimensional array.

In [36]:
arr3

array([[3, 7, 5, 8],
       [1, 4, 3, 6],
       [1, 9, 7, 4]])

In [37]:
list1 = [2,4,3,6,5,7,8,9,1,2,3,5]

In [38]:
len(list1)

12

In [39]:
list1 = np.array(list1)
arr4 = list1.reshape(3,4)

In [40]:
arr4

array([[2, 4, 3, 6],
       [5, 7, 8, 9],
       [1, 2, 3, 5]])

In [41]:
list1

array([2, 4, 3, 6, 5, 7, 8, 9, 1, 2, 3, 5])

In [42]:
arr1d = np.array([3,7,6,4,8])
len(arr1d)

5

In [44]:
arr1d

array([3, 7, 6, 4, 8])

In [43]:
arr1d[3]

4

In [45]:
arr1d[3] = 7

In [51]:
arr1d

array([ 3,  7,  6,  7,  8, 10, 10, 10])

In [53]:
arr1d = np.append(arr1d,10)

array([ 3,  7,  6,  7,  8, 10, 10, 10, 10, 10])

In [60]:
arr1d

array([ 3,  7,  6,  5,  5,  5,  7,  8, 10, 10, 10, 10, 10])

In [57]:
arr1d = np.insert(arr1d,3,5)

array([ 3,  7,  6,  5,  5,  5,  5,  7,  8, 10, 10, 10, 10, 10])

In [61]:
arr1d

array([ 3,  7,  6,  5,  5,  5,  7,  8, 10, 10, 10, 10, 10])

In [66]:
arr1d = np.delete(arr1d,6)

In [67]:
arr1d

array([ 3,  7,  6,  5,  7,  8, 10, 10, 10, 10])

np.delete(array,index)

This command is used to deletet particular element from the array.

In [69]:
list1 = [2,5,4,6]
list2 = [3,9,8,1]

In [70]:
arr2d = np.array([list1,list2])

In [71]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 1]])

In [72]:
list3 = [4,8,7,2]

In [74]:
arr2d = np.array([list1,list2,list3])

In [75]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 1],
       [4, 8, 7, 2]])

In [76]:
arr2d[1]

array([3, 9, 8, 1])

In [77]:
arr2d[0]

array([2, 5, 4, 6])

In [79]:
arr2d[:,2]

array([4, 8, 7])

In [80]:
arr2d[1][3] = 5

now we have updated one value.

In [81]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 5],
       [4, 8, 7, 2]])

In [82]:
new_row = [3,7,1,4]

In [83]:
arr2d = np.vstack([arr2d,new_row])

np.vstack() - This command is used to add a row in 2 dimensional array.

v stands for vertically.

In [84]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 5],
       [4, 8, 7, 2],
       [3, 7, 1, 4]])

In [86]:
new_column = np.array([3,8,7,2])

In [87]:
new_column = new_column.reshape(4,1)

new_column.reshape(4,1) is used to arrange elements in a proper column.

In [94]:
new_column

array([[3],
       [8],
       [7],
       [2]])

In [97]:
arr2d = np.hstack([arr2d,new_column])

np.hstack() - This command is used to add column in two dimensional array.

h stands for horizontally.

In [98]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [101]:
np.delete(arr2d,2,axis=0)

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [3, 7, 1, 4, 2]])

np.delete(array,index,index=0) - This command is used to delete particular a row temperarily.

Second argument is for the which row/column you have to delete.

index 0 is for the row.

In [102]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [105]:
np.delete(arr2d,2,axis=1)

array([[2, 5, 6, 3],
       [3, 9, 5, 8],
       [4, 8, 2, 7],
       [3, 7, 4, 2]])

np.delete(array,index,index=1) - This command is used to delete particular a column temperarily.

Second argument is for the which row/column you have to delete.

index 1 is for the column.

In [106]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [115]:
arr1d = np.array([3,6,5,2,7,6,9,1])

In [109]:
arr1d[:4]

array([3, 6, 5, 2])

In [110]:
arr1d[5:]

array([6, 9, 1])

In [111]:
arr1d[2:6]

array([5, 2, 7, 6])

In list you cannot perform specific operation on all the elements of list.
In array you can perform specific operation operation on all the elements of list.

In [113]:
arr1d[[2,5,3]]

array([5, 6, 2])

Previous command has printed elements of array whichever we have pass the array indexes.

In [117]:
sorted_arr1d = sorted(arr1d)

In [118]:
sorted_arr1d

[1, 2, 3, 5, 6, 6, 7, 9]

In [120]:
sorted_arr1d = sorted(arr1d,reverse = True)
sorted_arr1d

[9, 7, 6, 6, 5, 3, 2, 1]

In [121]:
arr1d

array([3, 6, 5, 2, 7, 6, 9, 1])

In [165]:
ind = np.where(arr1d>=4)

np.where() - This command is used to get the specified resultant array.

In [166]:
ind

(array([ 1,  2,  4,  5,  6,  9, 10, 13, 14], dtype=int64),)

by printing this array you will get the indexes of elements which are satisfied with the condition.
dtype=int64 is also a part of the array.

In [167]:
len(ind)

1

In [169]:
len(ind[0])

9

len(ind[0]) - This command gives the count of values that are greater than or equals to 4. Because in line number 124 we have used 'greater than or equals to 4' condition.

In [129]:
(arr1d>=4).sum()

5

(arr1d>=4).sum() - This command gives the count of values that are greater than or equals to 4. Because in line number 124 we have used 'greater than or equals to 4' condition.

In [130]:
type(ind)

tuple

In [168]:
arr1d[ind]

array([6, 5, 7, 6, 9, 5, 7, 5, 9])

In [132]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [133]:
ind2 = np.where(arr2d>=4)

In [134]:
ind2

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3], dtype=int64),
 array([1, 2, 3, 1, 2, 3, 4, 0, 1, 2, 4, 1, 3], dtype=int64))

In [135]:
len(ind2)

2

In [136]:
(arr2d>=4).sum()

13

(arr2d>=4).sum() - This command gives the count of values that are greater than or equals to 4. Because in line number 124 we have used 'greater than or equals to 4' condition.

In [139]:
len(ind2[0])

13

len(ind2[0]) - This command gives the count of values that are greater than or equals to 4. Because in line number 124 we have used 'greater than or equals to 4' condition.

In [142]:
arr1d

array([3, 6, 5, 2, 7, 6, 9, 1])

In [143]:
x = np.array([3,5,7,3,3,5,9,1,3])

In [144]:
arr1d = np.concatenate((arr1d,x))

In [145]:
arr1d

array([3, 6, 5, 2, 7, 6, 9, 1, 3, 5, 7, 3, 3, 5, 9, 1, 3])

In [146]:
np.unique(arr1d)

array([1, 2, 3, 5, 6, 7, 9])

np.unique(arr1d) - This command will print unique numbers from the given array.

In [148]:
5 in np.unique(arr1d)

True

5 in np.unique(arr1d) - This command is used to check weather the given value is there or not. If it is there it will return True else it will return False.

syntax - value in np.where(array)

In [152]:
np.in1d(arr1d,[2,7])

array([False, False, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False])

np.in1d(arr1d,[2,7]) - This command will check the given values into the specified array.

If the value is there in the array it will return True else it will return False.

syntax - np.in1d(array,[value,value])

In [153]:
np.where(np.in1d(arr1d,[2,7]))

(array([ 3,  4, 10], dtype=int64),)

Note - Input of the np.where() is condition and output of the np.where() command is indexes of resultant / where the condition is True.

In [158]:
ind3 = np.where(np.in1d(arr1d,[2,7]))

In [159]:
len(ind3[0])

3

In [173]:
x = np.array([4,7,6,3,9])

In [174]:
y = np.array([1,4,5,7,8])

In [175]:
np.union1d(x,y)

array([1, 3, 4, 5, 6, 7, 8, 9])

np.union1d(x,y) - It will return the union(either x or in y) of the mentioned array.

syntax - np.union1d(array,array)

In [178]:
np.intersect1d(x,y)

array([4, 7])

In [180]:
np.intersect1d(y,x)

array([4, 7])

np.intersect1d(x,y) , np.intersect1d(y,x) - It will return the intersection(common values) of the mentioned array.

np.intersect1d(array,array)

In [181]:
np.in1d(x,y)

array([ True,  True, False, False, False])

np.in1d(x,y) - This command will check the values of array x in the array of y. If value is there it will return True else it will return False.

In [182]:
np.in1d(y,x)

array([False,  True, False,  True, False])

In [185]:
x

array([4, 7, 6, 3, 9])

In [186]:
y

array([1, 4, 5, 7, 8])

np.in1d(y,x) - This command will check the values of array y in the array of x. If value is there it will return True else it will return False.

In [183]:
np.setdiff1d(x,y)

array([3, 6, 9])

np.setdiff1d(x,y) - It will return the 

In [184]:
np.setdiff1d(y,x)

array([1, 5, 8])

np.setdiff1d(y,x)