# data visualization



# plot graph by using data frame

for plotting we will use matplotlib
import matplotlib.pyplot as plt

1. for plotting a graph, we need to first set x and y value and pass it to plt.plot(x,y)
2. inorder to set label and title.

plotting a graph from data frame, we need pandas and matplotlib both.
we need to provide columns from data frame to graph plot.


# numpy

numpy is specially use for matrix manupulation

In [1]:
import numpy as np

In [2]:
m=np.array([[10,20,30,40],[12,23,34,45]])

In [3]:
print(m)

[[10 20 30 40]
 [12 23 34 45]]


In [4]:
m.shape #only if square or rectangle matrix or only number of rows

(2, 4)

In [5]:
m=np.array([[10,20,30,40],[12,23,34,45]])

if it is taken as one dimension like [10,20,30,40,50,60], then it gives 'n'(6)

In [9]:
m.ndim #- return dimension of given array.
#if sqaure or rectangular 1d,2d,3d else only 1d.

m.size

#if square or rectangular m.size returns number of elements otherwise returns number of rows

2

In [10]:
print(m.size)

8


In [11]:
m[0][2]

30

In [12]:
m=np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333]])

In [13]:
m.size

12

In [14]:
m.ndim

2

In [15]:
m.shape

(3, 4)

In [16]:
print(m)

[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]]


bydefult len returns number of rows, when given with row index will return number of column.

In [22]:
for i in m:
    for j in i:
        print(j)

11
22
33
44
55
66
77
88
99
111
222
333


In [23]:
for i in np.nditer(m[::]): #this method is used to slicing.
    print(i) 

11
22
33
44
55
66
77
88
99
111
222
333


In [28]:
n=np.arange(1,100,10)
print(n)

[ 1 11 21 31 41 51 61 71 81 91]


In [29]:
m.reshape(3,4)

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 111, 222, 333]])

In [37]:
#arange(start,end,step)
a=np.arange(1,24,2)
print(a.reshape(3,4))

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [39]:
print(c=np.arange(1,24,2).reshape(3,4))

TypeError: 'c' is an invalid keyword argument for print()

In [41]:
m=np.linspace(1,12,4)
print(m)

[ 1.          4.66666667  8.33333333 12.        ]


# randomization

to use random one must import random class by,
from numpy import random.

class is used for generating, int and fractional random numbers has 3 basic formats
for integer -> random.randint(n) - it will generate random number from 1-n


In [12]:
from numpy import random

In [13]:
print(random.randint(100))

55


In [14]:
print(random.randint(100,size=(6,6))) #used to get random integers within limit as mentioned in size

[[59 11 91 27 53 84]
 [67 28 85  6 37 68]
 [98  0  3 23  4 84]
 [13 58 18 41 24 91]
 [ 9 45 27 85 84 53]
 [94 11 77  8 37 92]]


In [17]:
random.choice(["a","b","c","d","e"])#used to get random choice

'b'

In [19]:
random.choice(["a","b","c","d","e"])#used to get random choice as mentioned in size

'c'

In [57]:
1. int, fractional

SyntaxError: invalid syntax (2066193352.py, line 1)

In [58]:
print(random.randint(50,size=(5,5)))

[[44 46 11 45  9]
 [41 47 21 41 24]
 [40 40 40  3 47]
 [20 32  5 37 27]
 [23 26 25  6 29]]


In [61]:
a=np.random.randint(50,size=(5,5))
print(a)

[[19 36 18  4  1]
 [10  0 21 14 17]
 [11  5 26 25 11]
 [26  0  0  1 38]
 [ 4 16 46 18  3]]


np.sort()-> it will sort content row wise


In [62]:
np.sort(a)

array([[ 1,  4, 18, 19, 36],
       [ 0, 10, 14, 17, 21],
       [ 5, 11, 11, 25, 26],
       [ 0,  0,  1, 26, 38],
       [ 3,  4, 16, 18, 46]])

In [63]:
np.sort(a,axis=0)

array([[ 4,  0,  0,  1,  1],
       [10,  0, 18,  4,  3],
       [11,  5, 21, 14, 11],
       [19, 16, 26, 18, 17],
       [26, 36, 46, 25, 38]])

In [66]:
v=np.where(a>=30)
print(v)

(array([0, 3, 4], dtype=int64), array([1, 4, 2], dtype=int64))


In [77]:
x=np.where(a>=10)
print(x)#list of x,y indexes that satisfies condition

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4], dtype=int64), array([0, 1, 2, 0, 2, 3, 4, 0, 2, 3, 4, 0, 4, 1, 2, 3], dtype=int64))


In [78]:
print(a[x])

[19 36 18 10 21 14 17 11 26 25 11 26 38 16 46 18]
