In [41]:
# Data Processing

# import libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
# import dataset
dataset=pd.read_csv("Data.csv")
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
# Purchase act as a classifiers for the dataset
# decision making :- salary>age>country
# purchase :- [y ] dependent peremiter / CLASSISFIERS imp
# salary,age,country :- independent columns [x]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [6]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [14]:
# neglect the last column
# Independent
x=dataset.iloc[:,:-1].values 
# dependent 
y=dataset.iloc[:,-1].values 

In [15]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [16]:
# Handling the missing values 
from sklearn.impute import SimpleImputer
imputer=SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [17]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [20]:
#Splitting the data into the training and testing datasets

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y,test_size=0.2,random_state=0)

In [22]:
x_train

array([['Germany', 40.0, 63777.77777777778],
       ['France', 37.0, 67000.0],
       ['Spain', 27.0, 48000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Spain', 38.0, 61000.0],
       ['France', 44.0, 72000.0],
       ['France', 35.0, 58000.0]], dtype=object)

In [23]:
x_test

array([['Germany', 30.0, 54000.0],
       ['Germany', 50.0, 83000.0]], dtype=object)

In [24]:
y_train

array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes'], dtype=object)

In [25]:
y_test

array(['No', 'No'], dtype=object)

# Encoding categorical data

In [26]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder=LabelEncoder()
x[:,0]=labelencoder.fit_transform(x[:,0])

In [27]:
# role of lable encoder
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

col_t=ColumnTransformer([('encoder',OneHotEncoder(),[0])])
x1=np.array(col_t.fit_transform(x),dtype=np.str_)


In [36]:
x1

array([['0.0', '1.0'],
       ['1.0', '0.0'],
       ['1.0', '0.0'],
       ['1.0', '0.0'],
       ['1.0', '0.0'],
       ['0.0', '1.0'],
       ['1.0', '0.0'],
       ['0.0', '1.0'],
       ['1.0', '0.0'],
       ['0.0', '1.0']], dtype='<U32')

# Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x1=sc_x.fit_transform(x1)
#x_test=sc_x.transform(x_test)

In [39]:
x1

array([[-1.22474487,  1.22474487],
       [ 0.81649658, -0.81649658],
       [ 0.81649658, -0.81649658],
       [ 0.81649658, -0.81649658],
       [ 0.81649658, -0.81649658],
       [-1.22474487,  1.22474487],
       [ 0.81649658, -0.81649658],
       [-1.22474487,  1.22474487],
       [ 0.81649658, -0.81649658],
       [-1.22474487,  1.22474487]])

In [40]:
# hw :[titanic]

In [42]:
df=pd.read_csv('titanic.csv')

In [43]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [45]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [46]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [53]:
#df.Pclass.unique() --> array([3, 1, 2], dtype=int64)
#df.Survived.unique() --> array([0, 1], dtype=int64)
#df.Sex.unique() --> array(['male', 'female'], dtype=object)


array(['male', 'female'], dtype=object)

In [61]:
df1=df[['PassengerId','Name','Age','Sex','Survived']]

In [62]:
df1

PassengerId                                               Name   Age  \
0              1                            Braund, Mr. Owen Harris  22.0   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0   
2              3                             Heikkinen, Miss. Laina  26.0   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0   
4              5                           Allen, Mr. William Henry  35.0   
..           ...                                                ...   ...   
886          887                              Montvila, Rev. Juozas  27.0   
887          888                       Graham, Miss. Margaret Edith  19.0   
888          889           Johnston, Miss. Catherine Helen "Carrie"   NaN   
889          890                              Behr, Mr. Karl Howell  26.0   
890          891                                Dooley, Mr. Patrick  32.0   

        Sex  Survived  
0      male         0  
1    female         1  
2    female         1  
3    female         1  
4      male         0  
..      ...       ...  
886    male         0  
887  female         1  
888  female         0  
889    male         1  
890    male         0  

[891 rows x 5 columns]

In [60]:
df1.Survived.unique()
df1.Sex.unique()

array(['male', 'female'], dtype=object)

In [72]:
x=df1.iloc[:,:-1].values
y=df1.iloc[:,-1].values  

In [71]:
x

array([[1, 'Braund, Mr. Owen Harris', 22.0, 'male'],
       [2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 38.0,
        'female'],
       [3, 'Heikkinen, Miss. Laina', 26.0, 'female'],
       ...,
       [889, 'Johnston, Miss. Catherine Helen "Carrie"', nan, 'female'],
       [890, 'Behr, Mr. Karl Howell', 26.0, 'male'],
       [891, 'Dooley, Mr. Patrick', 32.0, 'male']], dtype=object)

In [73]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [82]:
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(x[:,2:3]) # where to apply or fit the data
x[:,2:3]=imp.transform(x[:,2:3])

In [83]:
x

array([[1, 'Braund, Mr. Owen Harris', 22.0, 'male'],
       [2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 38.0,
        'female'],
       [3, 'Heikkinen, Miss. Laina', 26.0, 'female'],
       ...,
       [889, 'Johnston, Miss. Catherine Helen "Carrie"',
        29.69911764705882, 'female'],
       [890, 'Behr, Mr. Karl Howell', 26.0, 'male'],
       [891, 'Dooley, Mr. Patrick', 32.0, 'male']], dtype=object)

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [92]:
x_train

array([[141, 'Boulos, Mrs. Joseph (Sultana)', 29.69911764705882,
        'female'],
       [440, 'Kvillner, Mr. Johan Henrik Johannesson', 31.0, 'male'],
       [818, 'Mallet, Mr. Albert', 31.0, 'male'],
       ...,
       [630, "O'Connell, Mr. Patrick D", 29.69911764705882, 'male'],
       [560, 'de Messemaeker, Mrs. Guillaume Joseph (Emma)', 36.0,
        'female'],
       [685, 'Brown, Mr. Thomas William Solomon', 60.0, 'male']],
      dtype=object)

In [93]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,

In [94]:
x_test

array([[496, 'Yousseff, Mr. Gerious', 29.69911764705882, 'male'],
       [649, 'Willey, Mr. Edward', 29.69911764705882, 'male'],
       [279, 'Rice, Master. Eric', 7.0, 'male'],
       [32, 'Spencer, Mrs. William Augustus (Marie Eugenie)',
        29.69911764705882, 'female'],
       [256, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 29.0, 'female'],
       [299, 'Saalfeld, Mr. Adolphe', 29.69911764705882, 'male'],
       [610, 'Shutes, Miss. Elizabeth W', 40.0, 'female'],
       [319, 'Wick, Miss. Mary Natalie', 31.0, 'female'],
       [485, 'Bishop, Mr. Dickinson H', 25.0, 'male'],
       [368, 'Moussa, Mrs. (Mantoura Boulos)', 29.69911764705882,
        'female'],
       [705, 'Hansen, Mr. Henrik Juul', 26.0, 'male'],
       [347, 'Smith, Miss. Marion Elsie', 40.0, 'female'],
       [197, 'Mernagh, Mr. Robert', 29.69911764705882, 'male'],
       [536, 'Hart, Miss. Eva Miriam', 7.0, 'female'],
       [311, 'Hays, Miss. Margaret Bechstein', 24.0, 'female'],
       [15, 'Vestrom, Miss. H

In [95]:
y_test

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0], dtype=int64)

In [96]:
# Encoding 
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [97]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [99]:
lable_encoder=LabelEncoder()
x[:,3]=lable_encoder.fit_transform(x[:,3])

In [100]:
x

array([[1, 'Braund, Mr. Owen Harris', 22.0, 1],
       [2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 38.0,
        0],
       [3, 'Heikkinen, Miss. Laina', 26.0, 0],
       ...,
       [889, 'Johnston, Miss. Catherine Helen "Carrie"',
        29.69911764705882, 0],
       [890, 'Behr, Mr. Karl Howell', 26.0, 1],
       [891, 'Dooley, Mr. Patrick', 32.0, 1]], dtype=object)

In [101]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

c_t=ColumnTransformer([('encoder',OneHotEncoder(),[3])])
x_1=np.array(c_t.fit_transform(x),dtype=np.str_)

In [102]:
x_1

array([['0.0', '1.0'],
       ['1.0', '0.0'],
       ['1.0', '0.0'],
       ...,
       ['1.0', '0.0'],
       ['0.0', '1.0'],
       ['0.0', '1.0']], dtype='<U32')

In [103]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_1=sc_x.fit_transform(x_1)

In [104]:
x_1

array([[-0.73769513,  0.73769513],
       [ 1.35557354, -1.35557354],
       [ 1.35557354, -1.35557354],
       ...,
       [ 1.35557354, -1.35557354],
       [-0.73769513,  0.73769513],
       [-0.73769513,  0.73769513]])