# pip install openpyxl

- To install openpyxl library in your device.

In [1]:
import os

In [2]:
import numpy as np

In [3]:
os.getcwd()

'C:\\Users\\vaibh\\Statistics'

# os.getcwd()

- This command is used to get the current working directory.

In [5]:
os.chdir(r'C:Users\vaibh\Documents')
# This command will not work in online platform

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:Users\\vaibh\\Documents'

# os.chdir(r'directory path')

- This command is to change the current working directory.

In [6]:
x = np.array([3,5,4,5,7,6,8,9,7,2,3,4])

In [7]:
arr2d =  x.reshape(4,3)

In [8]:
arr2d

array([[3, 5, 4],
       [5, 7, 6],
       [8, 9, 7],
       [2, 3, 4]])

In [ ]:
np.save('myarray',arr2d)
# This comand will save your array at current working directory.

In [9]:
newarray = np.load('myarray.npy')
#This command will load your saved array into a new array.

FileNotFoundError: [Errno 2] No such file or directory: 'myarray.npy'

In [11]:
arr2d

array([[3, 5, 4],
       [5, 7, 6],
       [8, 9, 7],
       [2, 3, 4]])

In [ ]:
newarray

In [12]:
x = np.array([[3,7,5],[1,2,3]])

In [13]:
x

array([[3, 7, 5],
       [1, 2, 3]])

In [14]:
y = np.array([[1,7],[2,4],[8,1]])

In [15]:
y

array([[1, 7],
       [2, 4],
       [8, 1]])

# Note
- For multiplying 2 matrix, the number of columns of first matrix is should be the equals to the rows of the second matris and resultant matrix will be the number of rows of first one and the number of columns second one.

In [16]:
x.dot(y)

array([[57, 54],
       [29, 18]])

In [17]:
np.matmul(x,y)

array([[57, 54],
       [29, 18]])

# dot() and matmul()

- both of these methods have same output.

In [18]:
from numpy import linalg

In [19]:
from numpy.linalg import inv

# x + y + z = 6
# 2y + 5z = -4
# 2x + 5y - z = 27

In [20]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])

In [21]:
B = np.array([6,-4,27])

In [22]:
Ainv = np.linalg.inv(A)

In [23]:
Ainv

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

In [24]:
B = B.reshape(3,1)

In [25]:
B

array([[ 6],
       [-4],
       [27]])

In [26]:
Ainv.dot(B)

array([[ 5.],
       [ 3.],
       [-2.]])

In [27]:
from numpy import random

In [28]:
np.random.rand(10)

array([0.68285288, 0.34451654, 0.16258115, 0.64434404, 0.14165165,
       0.19901905, 0.74605823, 0.81195129, 0.59655504, 0.84741525])

# np.random.rand(10)

- This command will generate 10 random numbers.

In [31]:
x = np.random.rand(10)

In [32]:
y = np.round(x,3)

In [33]:
y

array([0.522, 0.318, 0.632, 0.929, 0.115, 0.554, 0.668, 0.924, 0.384,
       0.979])

In [34]:
np.random.randint(20,50)

28

# np.random.randint(starting range,ending range)

- This command will generate single integer number between starting range and ending range.

In [35]:
np.random.randint(20,50,5)

array([42, 37, 41, 41, 44])

# np.random.randint(starting range,ending range, number of elements)

- This command will generate as many numbers you want between starting range and ending range.
- Ex. np.random.randint(20,50,5)

In [36]:
x = np.random.rand(5)

In [37]:
y = np.round(x,3)

In [38]:
z = np.random.randint(20,50,5)

In [39]:
z + y

array([44.204, 46.172, 44.037, 27.763, 22.768])

In [43]:
!pip install openpyxl

In [45]:
import openpyxl as op

In [46]:
wb = op.load_workbook('Students.xlsx')

In [47]:
sht1 = wb['Kharghar']

In [48]:
sht1['A3'].value

'Rakesh'

In [49]:
x = sht1['B5'].value

In [50]:
x

'Statistics'

In [51]:
sht1.cell(3,1).value

'Rakesh'

In [52]:
sht1.cell(4,2).value

'ML PYHON'

In [53]:
sht1.max_row
# This command will give you the counnt of rows

5

In [55]:
sht1.max_column
# This command will give you the counnt of columns

3

In [56]:
# reading and data should start from rows #2 and finish at row #5
students = []

In [58]:
type(students)

list

In [59]:
len(students)

0

In [60]:
for ctr in range(2,6):
    x = sht1.cell(ctr,1).value
    students.append(x)

In [61]:
students

['Sudeep', 'Rakesh', 'Dhruv', 'Ruchita']

In [62]:
sht1.cell(ctr,3)

<Cell 'Kharghar'.C5>

In [63]:
sht1.cell(ctr,2)

<Cell 'Kharghar'.B5>

In [64]:
sht1.cell(ctr,1)

<Cell 'Kharghar'.A5>

In [65]:
for ctr in range(2,6):
    x = sht1.cell(ctr,3).value
    students.append(x)

In [66]:
students

['Sudeep', 'Rakesh', 'Dhruv', 'Ruchita', 68, 84, 73, 82]

In [68]:
marks = []

In [71]:
for ctr in range(2,6):
    x = sht1.cell(ctr,3).value
    marks.append(x)

In [72]:
marks

['Sudeep', 'Rakesh', 'Dhruv', 'Ruchita', 68, 84, 73, 82]

In [73]:
pl_name = ['Virat','Sachin','Dhoni','Rohit']
pl_score = [34534,868964,46464,87564]

In [74]:
wkbook = op.Workbook()

In [75]:
sht1 = wkbook.create_sheet('IPL')

In [76]:
sht1['A1'] = 'Name'

In [77]:
sht1['B1'] = 'Score'

In [78]:
wkbook.save('cricket.xlsx')

In [79]:
len(pl_name)

4

In [80]:
a = len(pl_name)

In [81]:
for ctr in range(2,a+2):
    x = pl_name[ctr-2]
    sht1.cell(ctr,1).value = x

In [82]:
for ctr in range(2,a+2):
    x = pl_score[ctr-2]
    sht1.cell(ctr,2).value = x

In [83]:
wkbook.save('cricket.xlsx')

In [84]:
import pandas as pd

In [85]:
x = [3,7,8,1,2]

In [89]:
type(x)

list

In [86]:
x[2]

8

In [87]:
ser1 = pd.Series(x)

In [88]:
ser1

0    3
1    7
2    8
3    1
4    2
dtype: int64

# ser1 = pd.Series(list_name)

- This command is used to create series with index value.
- Example - ser1 = pd.Series(x)

In [90]:
ser2 = pd.Series(x)
ser2 = pd.Series(x, index = ['A','B','C','D','E'])

In [91]:
ser2

A    3
B    7
C    8
D    1
E    2
dtype: int64

In [92]:
ser2[3]

1

In [93]:
ser2['D']

1

# ser2[index in integer value] & ser2['index in char value']

- Both of these commands have same output.
- These commands will return a value which is related to given index.

In [96]:
x = {'Sudeep':'Banglore','Sachin':'Mumbai','Virat':'Delhi','Ashwin':'Chennai'}
ser3 = pd.Series(x)

In [97]:
ser3

Sudeep    Banglore
Sachin      Mumbai
Virat        Delhi
Ashwin     Chennai
dtype: object

In [98]:
ser3['Sudeep'] = 'Mumbai'
ser3

Sudeep     Mumbai
Sachin     Mumbai
Virat       Delhi
Ashwin    Chennai
dtype: object

In [99]:
ser3[1] = 'Dubai'
ser3

Sudeep     Mumbai
Sachin      Dubai
Virat       Delhi
Ashwin    Chennai
dtype: object

In [102]:
new_pl = pd.Series(['Banglore','Kolkata'], index = ['ABD','Sehwag'])

In [103]:
ser3 = ser3.append(new_pl)
ser3

C:\Users\vaibh\AppData\Local\Temp\ipykernel_20972\1746866400.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser3 = ser3.append(new_pl)


Sudeep      Mumbai
Sachin       Dubai
Virat        Delhi
Ashwin     Chennai
ABD       Banglore
Sehwag     Kolkata
dtype: object

In [104]:
# list of list - Nested list

stu_info = [['Sudeep','Banglore',78],['Rakesh','Chennai',57],['Mayur','Mumbai',85],['Charu','Kharghar',80]]

In [105]:
len(stu_info)

4

In [107]:
stud_df = pd.DataFrame(stu_info, columns = ['Name','Location','Marks'])
stud_df

Name  Location  Marks
0  Sudeep  Banglore     78
1  Rakesh   Chennai     57
2   Mayur    Mumbai     85
3   Charu  Kharghar     80

In [123]:
pl_info = {'Name':['Sachin','Virat','Rohit','Ashwin'], 'Score':[3463,6453,3456,7634], 'Grade':['A','B','C','D']}

In [124]:
pl_df = pd.DataFrame(pl_info)
pl_df

Name  Score Grade
0  Sachin   3463     A
1   Virat   6453     B
2   Rohit   3456     C
3  Ashwin   7634     D

In [125]:
pl_df.at[2,'Grade'] = 'B'
pl_df

Name  Score Grade
0  Sachin   3463     A
1   Virat   6453     B
2   Rohit   3456     B
3  Ashwin   7634     D

In [126]:
pl_df.iat[3,2] = 'B'
pl_df

Name  Score Grade
0  Sachin   3463     A
1   Virat   6453     B
2   Rohit   3456     B
3  Ashwin   7634     B

# pl_df.at[row_data,column_data] = 'value'

In [119]:
new_pl = pd.DataFrame([['Jadeja',45632,'B'],['Dhoni',87654,'A']], columns = ['Players','Runs','Grade'])

In [120]:
new_pl

Players   Runs Grade
0  Jadeja  45632     B
1   Dhoni  87654     A

In [122]:
pl_df = pl_df.append(new_pl)
pl_df

C:\Users\vaibh\AppData\Local\Temp\ipykernel_20972\3435184131.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pl_df = pl_df.append(new_pl)


Name   Score Grade Players     Runs
0  Sachin  3463.0     A     NaN      NaN
1   Virat  6453.0     B     NaN      NaN
2   Rohit  3456.0     B     NaN      NaN
3  Ashwin  7634.0     B     NaN      NaN
0     NaN     NaN     B  Jadeja  45632.0
1     NaN     NaN     A   Dhoni  87654.0
0     NaN     NaN     B  Jadeja  45632.0
1     NaN     NaN     A   Dhoni  87654.0

In [127]:
new_pl = pd.DataFrame([['Jadeja',45632,'B'],['Dhoni',87654,'A']], columns = ['Name','Score','Grade'])

In [128]:
pl_df = pl_df.append(new_pl)

C:\Users\vaibh\AppData\Local\Temp\ipykernel_20972\4102215448.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pl_df = pl_df.append(new_pl)


In [129]:
pl_df

Name  Score Grade
0  Sachin   3463     A
1   Virat   6453     B
2   Rohit   3456     B
3  Ashwin   7634     B
0  Jadeja  45632     B
1   Dhoni  87654     A

In [130]:
pl_df.shape

(6, 3)

In [131]:
pl_df.index = range(pl_df.shape[0])
pl_df

Name  Score Grade
0  Sachin   3463     A
1   Virat   6453     B
2   Rohit   3456     B
3  Ashwin   7634     B
4  Jadeja  45632     B
5   Dhoni  87654     A

In [132]:
y = ['MI','RCB','MI','RR','CSK','CSK']
len(y)

6

In [133]:
pl_df['Team'] = y
pl_df

Name  Score Grade Team
0  Sachin   3463     A   MI
1   Virat   6453     B  RCB
2   Rohit   3456     B   MI
3  Ashwin   7634     B   RR
4  Jadeja  45632     B  CSK
5   Dhoni  87654     A  CSK