# Negative Binomial Regression

In [30]:
import numpy as np
import pandas as pd
import statsmodels
import sklearn
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [31]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='neg_bin')
df.head()

math      prog  daysabs
0    63  Academic        4
1    27  Academic        4
2    20  Academic        2
3    16  Academic        3
4     2  Academic        3

In [7]:
from statsmodels.discrete.discrete_model import NegativeBinomial as ngb

In [4]:
prog_dummy = pd.get_dummies(df['prog'],drop_first=True)

In [5]:
df = df.drop('prog',axis=1)

In [6]:
df = pd.concat([df,prog_dummy],axis=1)

In [8]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('daysabs',axis=1),df['daysabs'],test_size=0.25)

In [9]:
x_train = sm.add_constant(x_train,prepend=False)

In [13]:
df_train = pd.concat([x_train,y_train],axis=1)

In [14]:
mod1 = ngb.from_formula('daysabs ~ math + General + Vocational',data=df_train).fit()

Optimization terminated successfully.
         Current function value: 2.792394
         Iterations: 20
         Function evaluations: 26
         Gradient evaluations: 26


In [15]:
print(mod1.summary())

                     NegativeBinomial Regression Results                      
Dep. Variable:                daysabs   No. Observations:                  235
Model:               NegativeBinomial   Df Residuals:                      231
Method:                           MLE   Df Model:                            3
Date:                Thu, 22 Jun 2023   Pseudo R-squ.:                 0.02975
Time:                        09:38:12   Log-Likelihood:                -656.21
converged:                       True   LL-Null:                       -676.33
Covariance Type:            nonrobust   LLR p-value:                 9.463e-09
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.2444      0.151     14.819      0.000       1.948       2.541
math          -0.0067      0.003     -2.273      0.023      -0.012      -0.001
General        0.3274      0.226      1.447      0.1

math
Ho --> maths marks should not influence days of absent
Ha --> 

- As days of absent increases, marks gets decreases

In general days of absense > in Academic


In [16]:
pred_y = mod1.predict(x_test)

In [17]:
pred_y = round(mod1.predict(x_test))

In [18]:
pred_y

91     6.0
278    3.0
41     8.0
277    3.0
291    7.0
      ... 
58     8.0
76     8.0
285    3.0
171    3.0
64     8.0
Length: 79, dtype: float64

# Decision Tree

- It is used when data is categorical data.
- Whatever questions are asked,answers are always in yes or no.
- 

In [32]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='iris')
df.head()

Sepal_length  Sepal_width  Petal_length  Petal_width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
x_train = df.drop('Species',axis=1)

In [35]:
y_train = df.Species

In [36]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Species',axis=1),df['Species'],test_size = 0.25)

In [37]:
y_pred = mod1.predict(x_test)

In [38]:
mod1 = DecisionTreeClassifier().fit(x_train,y_train)

In [39]:
from sklearn.tree import export_graphviz

In [41]:
import pydotplus

In [42]:
export_graphviz(mod1,out_file='MyFile.dot')

# Random Forest

- The decision is not based on single tree.

In [22]:
from sklearn.ensemble import RandomForestClassifier as rfc

In [23]:
mod2 = rfc(n_estimators=20).fit(x_train,y_train)

In [24]:
y_pred = mod2.predict(x_test)

In [25]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 11  1]
 [ 0  0 12]]


In [26]:
mod2= rfc(n_estimators=20).fit(x_train,y_train)

In [27]:
y_pred = mod2.predict(x_test)

In [28]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 10  2]
 [ 0  0 12]]
