In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_excel('locations.xlsx',sheet_name='Salary')

In [3]:
df2 = pd.read_excel('locations.xlsx',sheet_name='Deptt')

In [4]:
df1

Name EmpID  Salary
0    Sudeep  A342      56
1   Deepika  J436      45
2    Chetan  B435      76
3  Abhishek  C234      47
4     Rishi  R475      38

In [5]:
df2

Name EmpID        Deptt
0   Sudeep  A342      Quality
1  Ruchika  C578        Sales
2  Deepika  J436        Admin
3    Arjun  A342  Procurement
4    Rishi  R475        Prodn

In [6]:
pd.merge(df1,df2)
#if we do not mentioned type of the join it has 'inner join' as bydefault join.

Name EmpID  Salary    Deptt
0   Sudeep  A342      56  Quality
1  Deepika  J436      45    Admin
2    Rishi  R475      38    Prodn

In [7]:
pd.merge(df1,df2,how='inner')

Name EmpID  Salary    Deptt
0   Sudeep  A342      56  Quality
1  Deepika  J436      45    Admin
2    Rishi  R475      38    Prodn

In [8]:
pd.merge(df1,df2,how='outer')

Name EmpID  Salary        Deptt
0    Sudeep  A342    56.0      Quality
1   Deepika  J436    45.0        Admin
2    Chetan  B435    76.0          NaN
3  Abhishek  C234    47.0          NaN
4     Rishi  R475    38.0        Prodn
5   Ruchika  C578     NaN        Sales
6     Arjun  A342     NaN  Procurement

In [9]:
pd.merge(df1,df2,how='left')

Name EmpID  Salary    Deptt
0    Sudeep  A342      56  Quality
1   Deepika  J436      45    Admin
2    Chetan  B435      76      NaN
3  Abhishek  C234      47      NaN
4     Rishi  R475      38    Prodn

In [10]:
pd.merge(df1,df2,how='right')

Name EmpID  Salary        Deptt
0   Sudeep  A342    56.0      Quality
1  Ruchika  C578     NaN        Sales
2  Deepika  J436    45.0        Admin
3    Arjun  A342     NaN  Procurement
4    Rishi  R475    38.0        Prodn

In [11]:
df1 = pd.read_excel('MaterialInfo.xlsx',sheet_name='Inventory')

In [12]:
df2 = pd.read_excel('MaterialInfo.xlsx',sheet_name='Info')

In [13]:
df1

MaterialID  Quantity
0           A        32
1           B        65
2           A        87
3           B        43
4           C        67
5           A        34
6           A        34
7           B        23
8           C        76
9           C        89
10          B        56
11          A        67
12          B        69
13          B        76

In [14]:
df2

MaterialID  Rate
0          A  1200
1          B  1500
2          C  2500

In [15]:
pd.merge(df1,df2)

MaterialID  Quantity  Rate
0           A        32  1200
1           A        87  1200
2           A        34  1200
3           A        34  1200
4           A        67  1200
5           B        65  1500
6           B        43  1500
7           B        23  1500
8           B        56  1500
9           B        69  1500
10          B        76  1500
11          C        67  2500
12          C        76  2500
13          C        89  2500

In [16]:
pd.merge(df1,df2,how='inner')

MaterialID  Quantity  Rate
0           A        32  1200
1           A        87  1200
2           A        34  1200
3           A        34  1200
4           A        67  1200
5           B        65  1500
6           B        43  1500
7           B        23  1500
8           B        56  1500
9           B        69  1500
10          B        76  1500
11          C        67  2500
12          C        76  2500
13          C        89  2500

In [17]:
pd.merge(df1,df2,how='outer')

MaterialID  Quantity  Rate
0           A        32  1200
1           A        87  1200
2           A        34  1200
3           A        34  1200
4           A        67  1200
5           B        65  1500
6           B        43  1500
7           B        23  1500
8           B        56  1500
9           B        69  1500
10          B        76  1500
11          C        67  2500
12          C        76  2500
13          C        89  2500

In [18]:
pd.merge(df1,df2,how='left')

MaterialID  Quantity  Rate
0           A        32  1200
1           B        65  1500
2           A        87  1200
3           B        43  1500
4           C        67  2500
5           A        34  1200
6           A        34  1200
7           B        23  1500
8           C        76  2500
9           C        89  2500
10          B        56  1500
11          A        67  1200
12          B        69  1500
13          B        76  1500

In [19]:
pd.merge(df1,df2,how='right')

MaterialID  Quantity  Rate
0           A        32  1200
1           A        87  1200
2           A        34  1200
3           A        34  1200
4           A        67  1200
5           B        65  1500
6           B        43  1500
7           B        23  1500
8           B        56  1500
9           B        69  1500
10          B        76  1500
11          C        67  2500
12          C        76  2500
13          C        89  2500

In [20]:
grades = np.array(['A','C','D','A','B','C','A','B','B','B','A','C','B','A','A','B','C'])

In [21]:
len(grades)

17

In [22]:
np.unique(grades)
#it will print unique elements from the array.

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [23]:
np.unique(grades, return_counts=True)
#it will return unique elements from the array with the count of the occurance.

(array(['A', 'B', 'C', 'D'], dtype='<U1'), array([6, 6, 4, 1], dtype=int64))

In [24]:
grd_count = np.unique(grades, return_counts=True)
#in this command, result will store inside a grd_count

In [25]:
grd_count[0]

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [26]:
grd_count[1]

array([6, 6, 4, 1], dtype=int64)

In [27]:
grd_props = grd_count[1] / len(grades)

In [28]:
grd_props

array([0.35294118, 0.35294118, 0.23529412, 0.05882353])

In [29]:
np.round(grd_props,3)

array([0.353, 0.353, 0.235, 0.059])

In [30]:
grd_pct = grd_props*100
grd_pct

array([35.29411765, 35.29411765, 23.52941176,  5.88235294])

In [32]:
np.cumsum(grd_pct)

array([ 35.29411765,  70.58823529,  94.11764706, 100.        ])

In [34]:
x = np.array([45,78,23,56,12])

In [35]:
np.argsort(x)
#this command will return you the indexes from lowest to the highest integer.

array([4, 2, 0, 3, 1], dtype=int64)

In [37]:
sorted(x)
#this command will return the values from the gievn array in ascending order.

[12, 23, 45, 56, 78]

# Central Tendancy

- mean
- median
- mode

# Variation of Dispersion

- range
- inter-quartile range
- variance
- std deviation

# Shape

- skewness
- kurtosis

In [38]:
mylist = [3,6,5,4,7,6,8,9,1,10,13,4,7,11,4,7,9]

In [39]:
sum(mylist) / len(mylist)

6.705882352941177

In [40]:
np.mean(mylist)

6.705882352941177

# Mean

- mean = sum of elements / length of elements.
- Example -> sum(list_name) / len(list_name).
- In numpy library there is one function to calculate mean.
- np.mean(list_name)

- 10 have value as 7 - 10*7
- 15 have value as 8 - 15*8
- 23 have value as 9 - 23*9
- 8 have value as 10 - 8*10

In [41]:
freq = np.array([10,15,23,8])

In [42]:
values = np.array([7,8,9,10])

In [43]:
freq*values/sum(freq) #weighted average

array([1.25      , 2.14285714, 3.69642857, 1.42857143])

In [44]:
sum(freq*values/sum(freq)) #weighted average

8.517857142857142

In [45]:
len(mylist)

17

In [46]:
sorted(mylist)[8]

7

In [47]:
np.median(mylist)

7.0

In [48]:
np.mean(mylist)

6.705882352941177

In [49]:
sal = [6,7,8,6,5,7,9,4,5,6,7,8,9,6,5,7,5]

In [50]:
np.mean(sal)

6.470588235294118

In [51]:
np.median(sal)

6.0

In [52]:
new_sal = [6,7,8,6,5,7,9,4,5,6,7,8,9,6,5,7,5,50,54,55,56,60]

In [53]:
np.mean(new_sal)

17.5

In [54]:
np.median(new_sal)

7.0

In [55]:
from collections import Counter

In [57]:
Counter(mylist).most_common()

[(4, 3),
 (7, 3),
 (6, 2),
 (9, 2),
 (3, 1),
 (5, 1),
 (8, 1),
 (1, 1),
 (10, 1),
 (13, 1),
 (11, 1)]

# Range

- range
- inter quartile range
- variance
- standard deviation
- range = max - min

In [58]:
max(mylist) - min(mylist)

12

# Drawbacks of range

- Easy to calculate
- It uses only 2 values from multiple values to calculate range.
- Calculation of range can get affected by the presence of these extreme values.

- IQR = third quartile - first quartile or 75th percentile - 25th percentile

In [60]:
np.percentile(mylist,75) - np.percentile(mylist,25)

5.0

In [63]:
x = [1,4,4,7,5,8,9,3,10]
x

[1, 4, 4, 7, 5, 8, 9, 3, 10]

In [64]:
y = [1,4,4,4,4,4,4,4,10]
y

[1, 4, 4, 4, 4, 4, 4, 4, 10]

In [65]:
np.percentile(x,75) - np.percentile(x,25)

4.0

In [66]:
np.percentile(y,75) - np.percentile(y,25)

0.0

In [67]:
x

[1, 4, 4, 7, 5, 8, 9, 3, 10]

In [68]:
np.var(x, ddof=0) #pop variance

8.0

In [69]:
np.var(x, ddof=1) #sample variance

9.0

In [70]:
np.var(x, ddof=0)**0.5 #pop std dev

2.8284271247461903

In [72]:
np.std(x, ddof=0) #pop std dev

2.8284271247461903

In [73]:
np.std(x, ddof=1) #sample std dev

3.0

In [74]:
np.std(x)

2.8284271247461903