# Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [3]:
#convert list into array
list1 = np.array(my_list)
list1

array([1, 2, 3, 4])

In [4]:
my_list2 = np.array(range(1,5))
my_list2

array([1, 2, 3, 4])

In [5]:
#printing the dimensions of the array


In [6]:
# 1D array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
# 2D array
b = np.array([[9,8,7],[6,5,4]])
b

array([[9, 8, 7],
       [6, 5, 4]])

In [8]:
#float array
c = np.array([[9.1,3.4,3.2],[6.7,9.6,5.8]])
c

array([[9.1, 3.4, 3.2],
       [6.7, 9.6, 5.8]])

In [9]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix #list of list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
a.shape

(3,)

In [11]:
#to check the size of the array in bytes
a.nbytes

24

In [12]:
np.array([[True,False],[False,True]])

array([[ True, False],
       [False,  True]])

In [13]:
x = np.array([1,2,3], dtype = 'int32')
x

array([1, 2, 3], dtype=int32)

In [14]:
type(x)

numpy.ndarray

In [15]:
x.dtype

dtype('int32')

In [16]:
#Random number
np.random.rand(4,2)

array([[0.98932827, 0.98916903],
       [0.25120361, 0.35067577],
       [0.17790079, 0.30893899],
       [0.52658381, 0.21974016]])

In [17]:
np.random.randn(3)

array([-0.78393755, -0.28506896,  0.66262574])

In [18]:
r = np.random.randint(1,200,10)
r
#generates random integer between the range

array([101, 103,  56, 105,  76, 125,  60, 117,  24,  82])

In [19]:
r.max()

125

In [20]:
np.identity(1)

array([[1.]])

In [21]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
m = np.array([1,2,3])
m

array([1, 2, 3])

In [23]:
m+2

array([3, 4, 5])

In [24]:
m*2

array([2, 4, 6])

In [25]:
m+m

array([2, 4, 6])

In [26]:
m**3

array([ 1,  8, 27])

In [27]:
#sqaure root
m**0.5

array([1.        , 1.41421356, 1.73205081])

In [28]:
np.sqrt(m)

array([1.        , 1.41421356, 1.73205081])

In [29]:
np.exp(m)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Pandas

In [30]:
import pandas as pd
#1. Series
#2. Data Frame

In [31]:
#creating series
s = pd.Series([1,'vaibhav',2,'tejaa',3,'surya',4,'preeti',5,'yogi'])
s

0          1
1    vaibhav
2          2
3      tejaa
4          3
5      surya
6          4
7     preeti
8          5
9       yogi
dtype: object

In [32]:
score = {'jane':90,'bill':80,'elon':85,'tom':75,'tim':95}
names = pd.Series(score)
names

jane    90
bill    80
elon    85
tom     75
tim     95
dtype: int64

In [33]:
names[names < 80]

tom    75
dtype: int64

In [34]:
names.isnull()

jane    False
bill    False
elon    False
tom     False
tim     False
dtype: bool

In [36]:
df = pd.read_csv('nyc_weather.csv')

In [37]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [38]:
df['Temperature'].max()

50

In [39]:
#est, events, rain
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [40]:
#mean of WindSpeedMPH
df['WindSpeedMPH'].mean()

6.892857142857143